#!/bin/bash

echo "🔧 修復.zshrc權限問題"
echo "========================================"

echo "當前.zshrc權限:"
ls -la ~/.zshrc 2>/dev/null || echo ".zshrc文件不存在"

echo ""
echo "問題: .zshrc文件所有者為root，無法編輯"
echo ""

echo "解決方案:"
echo ""
echo "方案1: 使用sudo修復權限 (需要密碼)"
echo "   sudo chown $(whoami):staff ~/.zshrc"
echo ""
echo "方案2: 創建新的.zshrc文件"
echo "   cp ~/.zshrc ~/.zshrc.backup"
echo "   echo '# OpenClaw別名' > ~/.zshrc.new"
echo "   echo 'alias openclaw=\"~/.npm-global/bin/openclaw\"' >> ~/.zshrc.new"
echo "   cat ~/.zshrc.backup >> ~/.zshrc.new"
echo "   mv ~/.zshrc.new ~/.zshrc"
echo ""
echo "方案3: 使用臨時配置文件"
echo "   echo 'alias openclaw=\"~/.npm-global/bin/openclaw\"' > ~/.openclaw_alias"
echo "   echo 'source ~/.openclaw_alias' >> ~/.zshrc"
echo ""

echo "========================================"
echo "🎯 推薦執行步驟"
echo "========================================"

echo "1. 首先備份當前.zshrc:"
echo "   cp ~/.zshrc ~/.zshrc.backup.$(date +%Y%m%d)"
echo ""
echo "2. 然後執行這個命令修復權限:"
echo "   sudo chown $(whoami):staff ~/.zshrc"
echo ""
echo "3. 輸入你的Mac密碼"
echo ""
echo "4. 添加別名:"
echo "   echo 'alias openclaw=\"~/.npm-global/bin/openclaw\"' >> ~/.zshrc"
echo ""
echo "5. 重新加載配置:"
echo "   source ~/.zshrc"
echo ""
echo "6. 測試:"
echo "   openclaw --version"
echo ""

echo "========================================"
echo "💡 臨時解決方案 (立即生效)"
echo "========================================"

echo "如果你不想處理權限問題，可以使用這些臨時方案:"
echo ""
echo "方案A: 在每個Terminal會話開始時執行:"
echo "   alias openclaw=\"~/.npm-global/bin/openclaw\""
echo ""
echo "方案B: 創建腳本文件:"
echo "   echo '#!/bin/bash' > ~/openclaw_new"
echo "   echo '~/.npm-global/bin/openclaw \"\$@\"' >> ~/openclaw_new"
echo "   chmod +x ~/openclaw_new"
echo "   # 然後使用: ~/openclaw_new --version"
echo ""
echo "方案C: 直接使用完整路徑:"
echo "   ~/.npm-global/bin/openclaw [命令]"
echo ""

echo "========================================"
echo "✅ 最簡單的立即方案"
echo "========================================"

echo "執行這個命令設置臨時別名 (只在當前Terminal有效):"
echo "   alias openclaw=\"~/.npm-global/bin/openclaw\""
echo ""
echo "然後測試:"
echo "   openclaw --version"
echo "   openclaw status"
echo ""
echo "這樣你就可以立即使用新版本，不需要修改.zshrc！"