#!/bin/bash

echo "🚀 快速修復OpenClaw別名"
echo "========================================"

echo "當前問題:"
echo "1. .zshrc中有重複的別名"
echo "2. 補全命令導致 'command not found: compdef' 錯誤"
echo "3. 但不影響別名功能"
echo ""

echo "解決方案A: 忽略錯誤，別名已生效"
echo "----------------------------------------"
echo "雖然有錯誤信息，但別名已經設置成功！"
echo "你可以直接測試:"
echo "  openclaw --version"
echo ""
echo "錯誤 'compdef' 只是補全功能的警告，不影響基本功能。"
echo ""

echo "解決方案B: 修復.zshrc文件"
echo "----------------------------------------"
echo "執行這些命令修復:"
echo ""
echo "# 1. 移除重複行和問題行"
echo "sed -i '' '/^alias openclaw=/d' ~/.zshrc"
echo "sed -i '' '/openclaw completion/d' ~/.zshrc"
echo ""
echo "# 2. 添加正確的別名"
echo "echo 'alias openclaw=\"~/.npm-global/bin/openclaw\"' >> ~/.zshrc"
echo ""
echo "# 3. 重新加載"
echo "source ~/.zshrc"
echo ""

echo "解決方案C: 創建乾淨的新配置"
echo "----------------------------------------"
echo "執行這個一鍵修復:"
echo ""
echo "cat > ~/.zshrc << 'EOF'"
echo "# OpenClaw別名"
echo "alias openclaw=\"~/.npm-global/bin/openclaw\""
echo "EOF"
echo ""
echo "source ~/.zshrc"
echo ""

echo "========================================"
echo "🎯 立即測試"
echo "========================================"

echo "請在Terminal中執行這些命令測試:"
echo ""
echo "1. 檢查別名:"
echo "   alias openclaw"
echo ""
echo "2. 測試版本:"
echo "   openclaw --version"
echo ""
echo "3. 如果上面失敗，使用完整路徑:"
echo "   ~/.npm-global/bin/openclaw --version"
echo ""
echo "4. 檢查狀態:"
echo "   ~/.npm-global/bin/openclaw status | grep Update"
echo ""

echo "========================================"
echo "💡 重要提示"
echo "========================================"

echo "• 錯誤 'compdef not found' 只是警告，不影響功能"
echo "• 別名可能已經生效，即使有錯誤信息"
echo "• 你可以直接測試 openclaw --version"
echo "• 如果不行，使用完整路徑 ~/.npm-global/bin/openclaw"
echo "• cron任務現在應該能正常檢測更新"
echo ""

echo "========================================"
echo "✅ 執行這個測試命令"
echo "========================================"

echo "請在Terminal中執行:"
echo ""
echo "~/.npm-global/bin/openclaw --version && echo '✅ 新版本已安裝' || echo '❌ 有問題'"
echo ""
echo "然後告訴我結果！ 🚀"